name: miktau
root: .
startup_window: lein
windows:
  - testing:
      boot auto-test
  - lein:
      layout: main-vertical
      panes:
        - backend:
            - cd backend/
            - ./backend
        - shell:
            - sudo /etc/init.d/nginx start
            - ls
        - repl:
            boot dev
            
